#!/usr/bin/env python3

import sys
import click


import check_entry_mariadb
import delete_old_entries
import detect_ldap_problems
import fix_wrong_format
import update_passwords
import delete_userpassword_cram
import modify_maildomain_dircount
from config_loader import load_config
from common import LOGGER


@click.group()
def cli():
    """CLI for submit lock accounts """
    pass


@cli.command()
@click.argument('input_file')
@click.option('--limit_days_ago', default=None)
@click.option('--number_of_accounts', default=None)
def delete_submit_locks(input_file, limit_days_ago, number_of_accounts):
    """Delete entries in ldap older than limit_days_ago before today
        :param input_file: File generated by check_submit_locks
        :param limit_days_ago: Date limit in days before current date to delete lock = submit
        :param number_of_accounts: Number of accounts to delete lock = submit
    """
    delete_old_entries.delete_old_entries(input_file, number_of_accounts=number_of_accounts,
                                          limit_days_ago=limit_days_ago)


@cli.command()
@click.argument('input_file')
@click.argument('pattern')
def detect_wrong_format(input_file, pattern):
    """Delete entries in ldap older than limit_days_ago before today
        :param input_file: Ldap dumb file to parse
        :param pattern: Pattern to be detected, it must be defined in config.yml!
    """
    cfg = load_config()
    try:
        cfg[pattern]
    except KeyError:
        LOGGER.error("Pattern not found in the config.yml file!")
        sys.exit(1)
    else:
        detect_ldap_problems.detect_wrong_format(cfg[pattern], input_file)


@cli.command()
@click.argument('input_file')
def delete_user_password_cram(input_file):
    """Delete userpasswordcram in ldap
        :param input_file: Ldap dumb file to parse
    """
    delete_userpassword_cram.delete_userpassword_cram(input_file)


@cli.command()
@click.argument('input_file')
@click.option('--number_of_accounts', default=10)
def fix_wrong_format(input_file, number_of_accounts):
    """Delete entries in ldap older than limit_days_ago before today
        :param input_file: File with the broken accounts ()
        :param number_of_accounts: Number of accounts to fix
    """
    fix_wrong_format.fix_wrong_format(input_file, number_of_accounts=number_of_accounts)


@cli.command()
@click.argument('input_file')
@click.option('--number_of_accounts', default=None)
@click.option('--first_account', default=0)
def update_password_fields(input_file, number_of_accounts, first_account):
    """Updates password fields in ldap using requests to PMAPI
        :param input_file: Ldap dumb file to parse
        :param number_of_accounts: Number of accounts to update
        :param first_account: First account in the dump file to start updating
    """
    update_passwords.update(input_file, number_of_accounts=number_of_accounts,
                                  first_account=first_account)


@cli.command()
@click.argument('input_file')
@click.option('--number_of_accounts', default=None)
@click.option('--first_account', default=0)
def update_maildomain_dircount(input_file, number_of_accounts, first_account):
    """Updates dircount mdbox for mail domains in ldap using requests to PMAPI
        :param input_file: Ldap dumb file to parse
        :param number_of_accounts: Number of accounts to update
        :param first_account: First account in the dump file to start updating
    """
    modify_maildomain_dircount.update(input_file, number_of_accounts=number_of_accounts,
                                      first_account=first_account)


if __name__ == '__main__':
    cli()
